/**
 * New layout system exports
 */

// Core base classes
export { 
  Element, 
  Shape, 
  Rectangle, 
  type Position, 
  type PositionConfig,
  type Theme,
  type Style,
  type Stylable,
  SwissTheme,
  defaultTheme,
  getTheme,
  createTheme,
  styleToSVGAttributes,
} from "./core/index.js";

// Artboard context (for auto-add to artboard)
export {
  getCurrentArtboard,
  setCurrentArtboard,
  clearCurrentArtboard,
} from "./core/ArtboardContext.js";

// Layout containers
export {
  Container,
  type ContainerConfig,
  type ContainerDirection,
  type HorizontalAlignment,
  type VerticalAlignment,
  type SizeMode,
  Grid,
  type GridConfig,
  type GridCell,
  Columns,
  type ColumnsConfig,
  type ColumnContainer,
} from "./layout/index.js";

// Elements
export {
  Artboard,
  Circle,
  Rect,
  Square,
  Triangle,
  Quadrilateral,
  Line,
  RegularPolygon,
  Text,
  TextArea,
  Latex,
  FunctionGraph,
  Side,
  Image,
  BezierCurve,
  Path,
  type ArtboardConfig,
  type CircleConfig,
  type RectConfig,
  type SquareConfig,
  type TriangleConfig,
  type TriangleType,
  type TriangleOrientation,
  type TriangleSide,
  type QuadrilateralConfig,
  type QuadrilateralType,
  type QuadrilateralSide,
  type LineConfig,
  type LineLabelConfig,
  type RegularPolygonConfig,
  type TextConfig,
  type TextAreaConfig,
  type HighlightedWord,
  type LatexConfig,
  type AnnotatedTextElement,
  type AnnotatedLatexElement,
  type FunctionGraphConfig,
  type PlottedFunction,
  type RemarkablePoint,
  type RemarkablePointType,
  type GraphAxis,
  type ShadedRegion,
  type SideConfig,
  type SideLabelConfig,
  type ImageConfig,
  type BezierCurveConfig,
  type PathConfig,
} from "./elements/index.js";

// Components
export {
  Arrow,
  Angle,
  BarChart,
  Bar,
  DonutChart,
  DonutSlice,
  LineChart,
  DataPoint,
  Chart,
  BarLayer,
  LineLayer,
  AreaLayer,
  ScatterLayer,
  RadarChart,
  type ArrowConfig,
  type AngleConfig,
  type BarChartConfig,
  type BarChartDataPoint,
  type BarSeries,
  type BarSegment,
  type BarChartRemarkablePoint,
  type BarChartRemarkablePointType,
  type DonutChartConfig,
  type DonutDataPoint,
  type DonutChartRemarkablePoint,
  type DonutChartRemarkablePointType,
  type LineChartConfig,
  type LineSeries,
  type LineChartDataPoint,
  type LineChartRemarkablePoint,
  type LineChartRemarkablePointType,
  type ChartConfig,
  type ChartLayer,
  type ChartContext,
  type BarLayerConfig,
  type LineLayerConfig,
  type AreaLayerConfig,
  type ScatterLayerConfig,
  type BarLayerDataPoint,
  type LineLayerDataPoint,
  type RadarChartConfig,
  type RadarSeries,
  type RadarChartRemarkablePoint,
  type RadarChartRemarkablePointType,
} from "./components/index.js";

// Utils
export {
  BoxAccessor,
  type BoxModel,
  type ParsedBoxModel,
  type BoxReference,
  parseBoxValue,
  parseBoxModel,
} from "./utils/index.js";

// Themed Components (web-like UI elements)
export {
  Card,
  type CardConfig,
  Legend,
  type LegendConfig,
  type LegendItem,
  Timeline,
  TimelinePeriodBar,
  TimelineEventMarker,
  type TimelineConfig,
  type TimelineEvent,
  type TimelinePeriod,
  type TimelineBreak,
  PeriodicElement,
  type ElementData,
  ElementCategory,
  type PeriodicElementConfig,
  PeriodicTable,
  type PeriodicTableConfig,
  ChemFig,
  ChemicalFormula,
  type ChemFigConfig,
  ChemicalStructures,
  ChemicalReactions,
  Treemap,
  type TreemapConfig,
  type TreemapNode,
  Alluvial,
  type AlluvialConfig,
  type AlluvialNode,
  type AlluvialFlow,
  type AlluvialStage,
} from "./themed-components/index.js";

